# render.yaml
services:
  - type: web
    name: house-price-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    autoDeploy: true
